### ISSUE TITLE
Checkout fails on Windows

### ISSUE THREAD

**Issue by celtic-coder** [arturo-lang/benchmarks#1]
Hi Yanis (@drkameleon),

The checkout of this repo fails on Windows with the following error:

![Windows-checkout-failed](https://user-images.githubusercontent.com/11787866/184624204-1bb6ecaa-b406-4005-9c3a-6cd605b0d458.png)

The question mark is an invalid character for a Windows filename:

`error: invalid path 'tests/library/collections/contains?_array_1m.art'`

I'm guessing that all the following files will prevent a checkout on the Windows platform:

![filenames-with-question-marks](https://user-images.githubusercontent.com/11787866/184625050-b3dd1387-a623-459e-aa9c-673334390586.png)

Kind Regards,
Liam

**Comment by drkameleon** [comment]
Liam, Hi!

The truth is I double-thought about the naming of the files, but given that I didn't expect anyone to play with this specific repo (other than having it used by our newly-introduced benchmarking toolset) I guess I - once again - missed Windows.

I'll fix it asap + manually correct the relevant data in the existing results. :)

Thanks!! 🚀

**Comment by drkameleon** [comment]
Well, let's see...

As I said, I've renamed all filenames with an `?` inside and, for reasons of consistency, also replaced the aforementioned filenames in all existing result data (in `/results`).

P.S. Still struggling a tiny bit with this repo, but after several days of work, I *think* I have managed to bring it to a fully functional state; or, at least, the whole thing is running automatically, without me having to do anything at all, which will hopefully help push Arturo toward the right direction, performance-wise 😉

**Comment by celtic-coder** [comment]
Thanks Yanis (@drkameleon)! 😃
